apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdsno.fullname" . }}-global
  labels:
    {{- include "pdsno.labels" . | nindent 4 }}
    app.kubernetes.io/component: global-controller
spec:
  type: {{ .Values.globalController.service.type }}
  ports:
    - port: {{ .Values.globalController.service.port }}
      targetPort: rest-api
      protocol: TCP
      name: rest-api
    - port: {{ .Values.globalController.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "pdsno.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: global-controller